apiVersion: v1
kind: Pod 
metadata:
  name: myfirstpod
  labels:
     app: myfirstapp
     function: IT
spec:
  containers:
    - name: mynginxcontainer
      image: nginx
      ports:
        - containerPort: 80
