apiVersion: v1
kind: Pod 
metadata:
  name: mymanualschpod
  labels:
     app: mymanualschapp
     function: IT
spec:
  containers:
    - name: mynginxcontainer
      image: nginx
      ports:
        - containerPort: 80
  nodeName: kubemaster

