apiVersion: v1
kind: Pod
metadata:
 name: hostpath-pd
spec:
 containers:
 - image: nginx
   name: hostpath-pd
   volumeMounts:
   - mountPath: /data
     name: test-volume
 volumes:
 - name: test-volume
   hostPath:
     # directory location on host
     path: /home/dinesh/data
     # this field is optional
     type: Directory